### ISSUE TITLE
Red Zone archives missing

### ISSUE THREAD

**Issue by Yattle190** [aqw/xbmc-gamepass#268]
Noticed on 0.91 and 0.92 that the Red Zone archives are no longer available. Is this something that is going to be permanent?

**Comment by aqw** [comment]
@Yattle190 this went missing in 0.9.1? Then this was unintentional, and was part of an effort to make the show acquisition for robust in 6ab1b0f669e25c89ec923e5389d072b816021e40

We'll take a look and see where we can find the RedZone archives in the XML. 

@BaumSchorle Do you have an idea why we're missing these?

---Alex

**Comment by aqw** [comment]
@Yattle190 I found the problem. RedZone is "special", or something, so it's info is returned separately from the rest of the shows...

Anyway, I have committed a fix, and it should work now. Please download the latest here from GitHub or wait a week or two for the next official release.

Thanks for taking the time to report this bug. :-)

---Alex

**Comment by Yattle190** [comment]
I  should be thanking all of you guys for the hard work.

I have the update and its working fine now :)

Keep up the good work. Its really appreciated.

**Comment by aqw** [comment]
@Yattle190 Glad to hear it's working. :-)

---Alex

**Comment by HenioH** [comment]
Is this for international subs? I don't see any Redzone archives anywhere in the addon... I downloaded and installed the current addon from here still don't see it.

**Comment by aqw** [comment]
@HenioH Everyone /should/ be able to access the RedZone Archives (in the NFL Network section). That being said, I don't have 'domestic' so I can't test and say for sure.

---Alex

**Comment by HenioH** [comment]
I don't see it under the NFL Network section in domestic. Ive updated to the version that's current on here. Maybe its hidden for domestic or not available?

**Comment by aqw** [comment]
@HenioH It must not be returned for domestic then. All the script does is look in the big-ass list of show info returned upon login, and then lists the shows in the UI. If there's no RedZone section in that list, then it won't be shown. :-/

If you enable debugging (both in Kodi and the addon) and attach a log here, I can confirm that this is what's going on for domestic. There's a /small/ chance that they're naming RedZone Archives differently for domestic users (which'd make little sense, but stranger things have happened).

---Alex

**Comment by HenioH** [comment]
Deng NFL contracts...ok will send in the morning im in Cali and about to crash out...

**Comment by Yattle190** [comment]
Hi, sorry to raise this again. Just noticed the redzone archives are missing today.

**Comment by salvatoreorange** [comment]
I can confirm (using international game pass), RedZone archives are still missing.

**Comment by aqw** [comment]
@Yattle190 @salvatoreorange What's not working for you? I have an international subscription and see the RedZone Archives (and they play). NFL Network -> 2016 -> RedZone Archives

Are you seeing something different?

---Alex
